#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js <<EOF
window.__APP_CONFIG__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",
  VITE_LIVEKIT_URL: "${VITE_LIVEKIT_URL:-}",
  VITE_LIVEKIT_AGENT_MODE: "${VITE_LIVEKIT_AGENT_MODE:-}",
  VITE_AURA_FEEDBACK_SECONDS: "${VITE_AURA_FEEDBACK_SECONDS:-300}",
  VITE_AGENT_TTS_PROVIDER: "${VITE_AGENT_TTS_PROVIDER:-openai}"
};
EOF
