#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js <<EOF
window.__APP_CONFIG__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",
  VITE_LIVEKIT_URL: "${VITE_LIVEKIT_URL:-}",
  VITE_LIVEKIT_SELF_HOSTED: "${VITE_LIVEKIT_SELF_HOSTED:-}",
  VITE_LIVEKIT_AGENT_MODE: "${VITE_LIVEKIT_AGENT_MODE:-}",
  VITE_DISABLE_BROWSER_TTS_FALLBACK: "${VITE_DISABLE_BROWSER_TTS_FALLBACK:-}",
  VITE_AUTO_SEND_SILENCE_MS: "${VITE_AUTO_SEND_SILENCE_MS:-}",
  VITE_TTS_PLAYBACK_RATE: "${VITE_TTS_PLAYBACK_RATE:-}"
};
EOF
